# SENTENCES_KEY= "sentences"
# ATTRIBUTES_KEY = "attributes"
ROOMS_SPECIFICATION_KEY = "roomsSpecification"
ROOMS_KEY= "rooms"
HAS_BALCONY_KEY= "hasBalcony"
STOREY_KEY = "storey"
TOTAL_STOREYS_KEY = "totalStoreys"
NUMBER_OF_BALCONIES_KEY= "numberOfBalconies"
FLAT_AREA_KEY= "flatArea"
HAS_ELEVATOR_KEY= "hasElevator"
FLAT_STATE_KEY= "flatState"
HAS_CELLAR_KEY= "hasCellar"
IS_INSULATED_KEY= "isInsulated"
HAS_RECONSTRUCTION_KEY= "hasReconstruction"
FLOOR_KEY= "floor"
COMPLEX_STATE_KEY= "complexState"
HAS_SEPARATE_TOILET_KEY= "hasSeparateToilet"
HAS_LOGGIE_KEY= "hasLoggie"
NUMBER_OF_CELLARS_KEY= "numberOfCellars"
PARKING_TYPE_KEY= "parkingType"
TOTAL_FLOOR_KEY= "totalFloors"
PRICE_KEY= "price"
LOGGIE_AREA_KEY= "loggieArea"
EQUIPMENT_KEY= "equipment"
ORIENTATION_KEY= "orientation"
CELLAR_AREA_KEY= "cellarArea"
HAS_TERRACE_KEY= "hasTerrace"
NUMBER_OF_TERRACES_KEY= "numberOfTerraces"
HAS_PARKING_KEY= "hasParking"
NUMBER_OF_PARKING_PLACES_KEY= "numberOfParkingPlaces"
PARKING_PRICE_KEY= "parkingPrice"
FLAT_RECONSTRUCTION_YEAR_KEY= "flatReconstructionYear"
COMPLEX_RECONSTRUCTION_YEAR_KEY= "complexReconstructionYear"
HAS_GARDEN_KEY= "hasGarden"
GARDEN_AREA_KEY= "gardenArea"
BALCONY_AREA_KEY= "balconyArea"
ATTIC_AREA_KEY= "atticArea"
COMPLEX_YEAR_KEY= "complexYear"
TERRACE_AREA_KEY= "terraceArea"
TOTAL_AREA_KEY= "totalArea"
HAS_GARAGE_KEY= "hasGarage"
NUMBER_OF_LOGGIE_KEY= "numberOfLoggie"
NUMBER_OF_LOGGIAS_KEY_V2 = "numberOfLoggias"
GARAGE_PRICE_KEY= "garagePrice"
GARAGE_AREA_KEY= "garageArea"
HEIGHT_KEY= "height"
FLAT_YEAR_KEY= "flatYear"
GARDEN_PRICE_KEY= "gardenPrice"
AMENITY_KEY = "amenity"
AVIABILITY_KEY = "aviability"
COMPLEX_EQUIPMENT_KEY = "complexEquipment"
COMPLEX_MODIFICATION_KEY = "complexModification"
FLAT_MODIFICATION_KEY = "flatModification"
GARAGE_PARKING_KEY = "garageParking"
HARD_EQUIPMENT_KEY = "hardEquipment"
HAS_ATTIC_KEY = "hasAttic"
LOCATION_KEY = "location"
PAYMENT_KEY = "payment"
PORMO_KEY = "pormo"
PRIVATE_PARKING_KEY = "privateParking"
PROMO_KEY = "promo"
PUBLIC_PARKING_KEY = "publicParking"
RESIDENTAL_PARKING_KEY = "residentalParking"
SOFT_EQUIPMENT_KEY = "softEquipment"
STOREY_KEY = "storey"
SUBJECTIVE_KEY = "subjective"
TOTAL_STOREYS_KEY = "totalStoreys"
TRANSPORT_KEY = "transport"
USELESS_KEY = "useless"
UTILITY_NETWORK_KEY = "utilityNetworks"
ELECTRIC_CERTIFICATE_KEY = "electricCertificate"
FLAT_MODIFICATION_YEAR_KEY = "flatModificationYear"
COMPLEX_MODIFICATION_YEAR_KEY = "complexModificationYear"
IS_SECTION_HEADER_KEY = "isSectionHeader"
FLAT_AREA_REASONING_KEY = "flatArea_reasoning"
HAS_SEPARATE_TOILET_SUBJECTIVE_KEY = "hasSeparateToilet_subjective"
ROOMS_SUBJECTIVE_KEY = "rooms_subjective"
TOTAL_FLOORS_REASONING_KEY = "totalFloors_reasoning"
FLAT_MODIFICATION_YEAR_RANGE_KEY = "flatModificationYear_range"
FLOOR_SUBJECTIVE_KEY = "floor_subjective"
TOTAL_STOREYS_REASONING_KEY = "totalStoreys_reasoning"
HAS_TERRACE_REASONING_KEY = "hasTerrace_reasoning"

ROOMS_REASONING_KEY = "rooms_reasoning"
FLOOR_REASONING_KEY = "floor_reasoning"
STOREY_REASONING_KEY = "storey_reasoning"
HAS_ELEVATOR_REASONING_KEY = "hasElevator_reasoning"
HAS_GARAGE_SUBJECTIVE_KEY = "hasGarage_subjective"
HAS_LOGGIE_REASONING_KEY = "hasLoggie_reasoning"
HAS_BALCONY_REASONING_KEY = "hasBalcony_reasoning"
STOREY_REASONING_KEY = "storey_reasoning"


TEXT_ATTRIBUTES_KEY = "textAttributes"
SAMPLE_SENTENCES_KEY = "sentences"
SENTENCE_ATTRIBUTES_KEY = "tags"
SAMPLE_ID_KEY = "id"


SELECTED_APARTMENT_ATTRIBUTES = {
    ROOMS_KEY, FLAT_AREA_KEY, FLOOR_KEY, HAS_CELLAR_KEY, HAS_SEPARATE_TOILET_KEY, HAS_PARKING_KEY,
    HAS_BALCONY_KEY, PRICE_KEY, HAS_LOGGIE_KEY, CELLAR_AREA_KEY, HAS_GARAGE_KEY, HAS_TERRACE_KEY, TOTAL_AREA_KEY, 
    BALCONY_AREA_KEY, TERRACE_AREA_KEY, FLAT_MODIFICATION_YEAR_KEY, HAS_GARDEN_KEY, LOGGIE_AREA_KEY, NUMBER_OF_BALCONIES_KEY,
    NUMBER_OF_LOGGIE_KEY, NUMBER_OF_CELLARS_KEY, FLAT_YEAR_KEY, GARDEN_AREA_KEY, FLAT_YEAR_KEY, 
    GARDEN_AREA_KEY, PARKING_PRICE_KEY, GARAGE_PRICE_KEY, HAS_ATTIC_KEY, GARAGE_AREA_KEY, NUMBER_OF_TERRACES_KEY, GARDEN_PRICE_KEY, STOREY_KEY }

SELECTED_APARTMENT_ATTRIBUTES_V2 = {
    ROOMS_KEY, FLAT_AREA_KEY, FLOOR_KEY, HAS_CELLAR_KEY, HAS_SEPARATE_TOILET_KEY, HAS_PARKING_KEY,
    HAS_BALCONY_KEY, PRICE_KEY, HAS_LOGGIE_KEY, CELLAR_AREA_KEY, HAS_GARAGE_KEY, HAS_TERRACE_KEY, TOTAL_AREA_KEY, 
    BALCONY_AREA_KEY, TERRACE_AREA_KEY, FLAT_MODIFICATION_YEAR_KEY, HAS_GARDEN_KEY, LOGGIE_AREA_KEY, NUMBER_OF_BALCONIES_KEY,
    NUMBER_OF_LOGGIAS_KEY_V2, NUMBER_OF_CELLARS_KEY, FLAT_YEAR_KEY, GARDEN_AREA_KEY, FLAT_YEAR_KEY, 
    GARDEN_AREA_KEY, PARKING_PRICE_KEY, GARAGE_PRICE_KEY, HAS_ATTIC_KEY, GARAGE_AREA_KEY, NUMBER_OF_TERRACES_KEY, GARDEN_PRICE_KEY, STOREY_KEY }

SELECTED_COMPLEX_ATTRIBUTES = {
    HAS_ELEVATOR_KEY, IS_INSULATED_KEY, TOTAL_FLOOR_KEY,COMPLEX_YEAR_KEY, COMPLEX_MODIFICATION_YEAR_KEY, TOTAL_STOREYS_KEY
}

ALL_SELECTED_ATTRIBUTES = SELECTED_APARTMENT_ATTRIBUTES | SELECTED_COMPLEX_ATTRIBUTES
ALL_SELECTED_ATTRIBUTES_V2 = SELECTED_APARTMENT_ATTRIBUTES_V2 | SELECTED_COMPLEX_ATTRIBUTES

MAX_RETRIES = 3
TEMPERATURE = 0.1
SEED = 12345
STORE_AFTER = 5
MAX_TOKENS = 2048